In [1]:
import pandas as pd
import sqlite3

In [2]:
games = pd.read_csv("cleaned_games.csv")

sales = pd.read_csv("cleaned_vgsales.csv")

merged = pd.read_csv("merged_games_sales.csv")

In [3]:
conn = sqlite3.connect("videogame.db")

cursor = conn.cursor()

print("Database connected successfully")

Database connected successfully

In [4]:
games.to_sql(
    'games',
    conn,
    if_exists='replace',
    index=False
)

sales.to_sql(
    'sales',
    conn,
    if_exists='replace',
    index=False
)

merged.to_sql(
    'merged_games_sales',
    conn,
    if_exists='replace',
    index=False
)

print("Tables created successfully")

Tables created successfully

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

                 name
0               games
1               sales
2  merged_games_sales

SQL QUERY

In [6]:
#1 Top Rated Games

query = """
SELECT Title, Rating
FROM games
ORDER BY Rating DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                               Title  Rating
0  Elden Ring: Shadow of the Erdtree     4.8
1       Disco Elysium: The Final Cut     4.6
2                        Outer Wilds     4.6
3                      Disco Elysium     4.6
4       Umineko: When They Cry Chiru     4.6
5        Bloodborne: The Old Hunters     4.6
6       Disco Elysium: The Final Cut     4.6
7                        Outer Wilds     4.6
8                      Disco Elysium     4.6
9       Umineko: When They Cry Chiru     4.6

In [7]:
#2 Best Selling Platforms

query = """
SELECT Platform,
SUM(Global_Sales) AS Total_Sales
FROM sales
GROUP BY Platform
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Platform  Total_Sales
0      PS2      1255.64
1     X360       979.96
2      PS3       957.84
3      Wii       926.71
4       DS       822.49
5       PS       730.66
6      GBA       318.50
7      PSP       296.28
8      PS4       278.10
9       PC       258.82

In [8]:
#3 Top Publishers

query = """
SELECT Publisher,
SUM(Global_Sales) AS Total_Sales
FROM sales
GROUP BY Publisher
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                      Publisher  Total_Sales
0                      Nintendo      1786.56
1               Electronic Arts      1110.32
2                    Activision       727.46
3   Sony Computer Entertainment       607.50
4                       Ubisoft       474.72
5          Take-Two Interactive       399.54
6                           THQ       340.77
7  Konami Digital Entertainment       283.64
8                          Sega       272.99
9            Namco Bandai Games       254.09

In [9]:
#4 Most Wishlisted Games

query = """
SELECT Title, Wishlist
FROM games
ORDER BY Wishlist DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                       Title  Wishlist
0  The Legend of Zelda: Tears of the Kingdom    5400.0
1                                 Elden Ring    4800.0
2                                 Elden Ring    4800.0
3                                 Elden Ring    4800.0
4                                      Omori    3800.0
5                                      Omori    3800.0
6                                      Omori    3800.0
7        NieR Replicant ver.1.22474487139...    3700.0
8        NieR Replicant ver.1.22474487139...    3700.0
9        NieR Replicant ver.1.22474487139...    3700.0

In [10]:
#5 Genre with Highest Global Sales

query = """
SELECT Genre,
SUM(Global_Sales) AS Total_Sales
FROM merged_games_sales
GROUP BY Genre
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

           Genre  Total_Sales
0         Action       960.51
1       Platform       643.09
2        Shooter       532.48
3   Role-Playing       396.83
4         Sports       279.60
5         Racing       198.01
6         Puzzle       135.33
7           Misc       133.87
8       Fighting        87.06
9      Adventure        65.04
10    Simulation        35.06
11      Strategy        13.22

In [11]:
#6 Platform with Most High Rated Games

query = """
SELECT Platform,
COUNT(*) AS High_Rated_Games
FROM merged_games_sales
WHERE Rating >= 4
GROUP BY Platform
ORDER BY High_Rated_Games DESC;
"""

pd.read_sql(query, conn)

   Platform  High_Rated_Games
0        PC                53
1       PS3                52
2      X360                48
3       PS2                46
4        PS                31
5       PS4                27
6        DS                22
7      SNES                21
8        GC                19
9       Wii                18
10      GBA                17
11     WiiU                16
12      3DS                16
13      N64                15
14     XOne                14
15       XB                12
16      PSV                11
17      NES                 6
18      PSP                 5
19       GB                 4
20      SAT                 1

In [12]:
#7 Regional Sales Comparison

query = """
SELECT
SUM(NA_Sales) AS North_America,
SUM(EU_Sales) AS Europe,
SUM(JP_Sales) AS Japan,
SUM(Other_Sales) AS Other_Regions
FROM sales;
"""

pd.read_sql(query, conn)

   North_America   Europe    Japan  Other_Regions
0        4392.95  2434.13  1291.02         797.75

In [13]:
#8 Average Rating Per Genre

query = """
SELECT Genres,
AVG(Rating) AS Average_Rating
FROM games
GROUP BY Genres
ORDER BY Average_Rating DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                              Genres  Average_Rating
0                              ['Indie', 'Platform']             4.5
1              ['Adventure', 'Strategy', 'Tactical']             4.5
2  ['Adventure', 'Indie', 'Puzzle', 'Simulator', ...             4.5
3  ['Adventure', 'Brawler', 'Platform', 'RPG', 'S...             4.5
4  ['Indie', 'RPG', 'Simulator', 'Strategy', 'Tur...             4.4
5  ['Adventure', 'Simulator', 'Strategy', 'Tactic...             4.4
6  ['Adventure', 'RPG', 'Simulator', 'Strategy', ...             4.4
7           ['Music', 'Platform', 'Racing', 'Sport']             4.3
8  ['Adventure', 'Puzzle', 'Simulator', 'Visual N...             4.3
9                 ['Adventure', 'Puzzle', 'Shooter']             4.3

In [14]:
#9 Top 10 Global Best Sellers

query = """
SELECT Name,
Global_Sales
FROM sales
ORDER BY Global_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                        Name  Global_Sales
0                 Wii Sports         82.74
1          Super Mario Bros.         40.24
2             Mario Kart Wii         35.82
3          Wii Sports Resort         33.00
4   Pokemon Red/Pokemon Blue         31.37
5                     Tetris         30.26
6      New Super Mario Bros.         30.01
7                   Wii Play         29.02
8  New Super Mario Bros. Wii         28.62
9                  Duck Hunt         28.31

In [15]:
#10 Wishlist vs Sales Analysis

query = """
SELECT Title,
Wishlist,
Global_Sales
FROM merged_games_sales
ORDER BY Wishlist DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Title  Wishlist  Global_Sales
0  Bloodborne    3300.0          2.38
1  Bloodborne    3300.0          2.38
2  Bloodborne    3300.0          2.38
3  God of War    2600.0          4.45
4  God of War    2600.0          4.45
5  God of War    2600.0          4.45
6   Bayonetta    2300.0          1.23
7   Bayonetta    2300.0          0.94
8   Bayonetta    2300.0          1.23
9   Bayonetta    2300.0          0.94

In [16]:
conn.close()

print("Database connection closed")

Database connection closed